#!/bin/bash

WIDTH="2160"
HEIGHT="-1"
FORMAT_LIST=("jpg" "JPG" "jpeg" "JPEG" "png" "PNG" "bmp" "BMP" "tiff" "TIFF" "avi" "AVI")

for x in "$@";do
    # is folder
    if [ -d "$x" ]; then
        for format in ${FORMAT_LIST[@]};do
            for y in "$x"/*.$format;do
                if [ -f $y ];then
                    echo $y
                    # folder -> file
                    ffmpeg -i "$y" -vf "scale=$WIDTH:$HEIGHT" "${y%.*}-${WIDTH}p.png"
                fi
            done
        done
    # is file
    else
        # file
        echo "$x"
        ffmpeg -i "$x" -vf "scale=$WIDTH:$HEIGHT" "${x%.*}-${WIDTH}p.png"
    fi

done