#!/bin/bash

# WIDTH="144"
# HEIGHT="-1"
FPS="30"
FORMAT_LIST=("mp4" "MP4" "avi" "AVI" "mov" "MOV" "webm" "WEBM")

for x in "$@";do
    # is folder
    if [ -d "$x" ]; then
        for format in ${FORMAT_LIST[@]};do
            for y in "$x"/*.$format;do
                if [ -f $y ];then
                    mkdir -p ${y%.*}-10fps/
                    echo $y
                    # folder -> file
                    ffmpeg -i "$y" -vcodec png -r $FPS ${y%.*}-${FPS}fps/image_%05d.png
                fi
            done
        done
    # is file
    else
        # file
        echo "$x"
        mkdir -p ${y%.*}-10fps/
        ffmpeg -i "$x" -vcodec png -r $FPS ${y%.*}-${FPS}fps/image_%05d.png
    fi
done
