#!/bin/bash

WIDTH="240"
HEIGHT="-1"
FORMAT_LIST=("mp4" "MP4" "avi" "AVI" "mov" "MOV" "webm" "WEBM")

for x in "$@";do
    # is folder
    if [ -d "$x" ]; then
        for format in ${FORMAT_LIST[@]};do
            for y in "$x"/*.$format;do
                if [ -f $y ];then
                    echo $y
                    # folder -> file
                    ffmpeg -i "$y" -vf "scale=$WIDTH:$HEIGHT" "${y%.*}-${WIDTH}p.mp4"
                fi
            done
        done
    # is file
    else
        # file
        echo "$x"
        ffmpeg -i "$x" -vf "scale=$WIDTH:$HEIGHT" "${x%.*}-${WIDTH}p.mp4"
    fi

done